### ISSUE TITLE
Request: play sound effect example

### ISSUE THREAD

**Issue by GValiente** [AntonioND/gbt-player#23]
It would be nice to have a proper example of playing sound effects with gbt-player.

From gbadev Discord server:
```
you can do something like

    disable channel 4 from the player
    play sound effect
    wait until it's done
    enable channel 4

**Comment by AntonioND** [comment]
Actually, I've just checked and there is something like that already: https://github.com/AntonioND/gbt-player/tree/4ee745f848d1aa610529aca0043f91cbc7d9ef6f/gba/examples/disable_channels

This example lets you play a sound effect in channel 2, and it lets you experiment with disabling the channel or not so that you can see that the sound effect can be interrupted if the channel is enabled. Is this good enough for you, or would you prefer a more explicit example? It would do basically the same thing.

**Comment by GValiente** [comment]
It seems good enough, thanks.
